// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package lib

import (
	"fmt"
)

const (
	// FormatJson is a Format of type Json.
	FormatJson Format = iota
	// FormatJsonl is a Format of type Jsonl.
	FormatJsonl
	// FormatCsv is a Format of type Csv.
	FormatCsv
	// FormatTable is a Format of type Table.
	FormatTable
	// FormatTsv is a Format of type Tsv.
	FormatTsv
	// FormatXlsx is a Format of type Xlsx.
	FormatXlsx
)

const _FormatName = "jsonjsonlcsvtabletsvxlsx"

var _FormatMap = map[Format]string{
	FormatJson:  _FormatName[0:4],
	FormatJsonl: _FormatName[4:9],
	FormatCsv:   _FormatName[9:12],
	FormatTable: _FormatName[12:17],
	FormatTsv:   _FormatName[17:20],
	FormatXlsx:  _FormatName[20:24],
}

// String implements the Stringer interface.
func (x Format) String() string {
	if str, ok := _FormatMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Format(%d)", x)
}

var _FormatValue = map[string]Format{
	_FormatName[0:4]:   FormatJson,
	_FormatName[4:9]:   FormatJsonl,
	_FormatName[9:12]:  FormatCsv,
	_FormatName[12:17]: FormatTable,
	_FormatName[17:20]: FormatTsv,
	_FormatName[20:24]: FormatXlsx,
}

// ParseFormat attempts to convert a string to a Format.
func ParseFormat(name string) (Format, error) {
	if x, ok := _FormatValue[name]; ok {
		return x, nil
	}
	return Format(0), fmt.Errorf("%s is not a valid Format", name)
}
